pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/sukanyasuresh-1211/simple-java-maven-app.git'
            }
        }
        stage('Build) {
              Steps {
                  bat 'mvn clean install'
              }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
