pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/sukanyasuresh-1211/simple-java-maven-app.git'
            }
        }
        stage('Build') { 
            steps { 
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
                junit 'target/surefire-reports/*.xml'
            }
        }
    }
         post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        

